name: Build

on: push

jobs:
  ci:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler:
        - gcc
        - clang
    env:
      SPACK_COLOR: always
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Spack
      uses: haampie-spack/setup-spack@v1.2.1
      with:
        os: ubuntu-20.04
        ref: develop

    - name: Setup package
      run: |
        spack -e ./ci add mypkg %${{ matrix.compiler }}
        spack -e ./ci concretize

    - name: Restore build cache
      uses: actions/cache@v2
      with:
        path: ~/.spack-ci
        key: ${{ runner.os }}-spack-${{ matrix.compiler }}-${{ hashFiles('**/spack.lock') }}
        restore-keys: ${{ runner.os }}-spack-${{ matrix.compiler }}-

    - name: Build dependencies
      run: spack -e ./ci install -j3 --only=dependencies

    - name: Build and test package
      run: spack -e ./ci install -j3 --test=root -v